// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgwkctjrjpfdfgjbfgqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impnd2tjdGpyanBmZGZnamJmZ3F1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUxNDczNjgsImV4cCI6MjA1MDcyMzM2OH0.nzoLI671_fpkr8Ar5OqsqnW-3WbCky_J-DITR_5Hzjs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);